### ISSUE TITLE
What's the timeline?

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-infra/fedora-messaging#106]
Hi, what's the timeline for Fedora Messaging? When can we expect it to be in prod? When can we start migrating from fedmsg to fedora-messaging?

I didn't find anything on Fedora wiki, hence asking here.

**Comment by jeremycline** [comment]
Hi @TomasTomecek,

The broker and fedmgs<->AMQP bridges have been in staging for some time now and the broker is now deployed in production. The bridges in production should be set up in the next day or two, so you can start migrating immediately. If you run into any trouble or have questions the documentation doesn't answer, please file bugs!
