### ISSUE TITLE
Provide a set of APIs for users outside Fedora infrastructure

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fedora-messaging#115]
https://github.com/fedora-infra/fedora-messaging/issues/111 shows we don't have a good path forward for users who are running production consumers outside Fedora infrastructure. The reason for this is that allowing unauthenticated access to the AMQP broker is a recipe for DoS attacks and the broker is a core piece of infrastructure (especially if/when other apps start using it for tasking systems in addition to general pub/sub).

The best option at the moment is to just keep using fedmsg, relying on the fact that bridges exist between AMQP and ZMQ. While this works, it's less than ideal for several reasons:

- No schema validation, Python APIs to interact with messages

- The interface you use to implement consumers depends on whether or not your service is inside Fedora infrastructure, and you have to change depending on where your service runs.

- fedmsg doesn't separate message headers from the message body, so bridging involves mangling messages. This means consumers outside have a different format to deal with which won't be documented (although it will be the same as the fedmsg messages sent today).

It would probably be best to create some tools so that the consumers outside infra can use the same interfaces. We would need:

- A documented wire format for ZMQ that can represent the AMQP messages. This would likely be a 3 part message in the format ``[<amqp topic>, <amqp headers>, <amqp body>]`` although we may want to include additional properties here.

- Something to publish the messages via ZMQ. This would be nearly identical to the AMQP->ZMQ bridge we have today, but it would use the wire format from above rather than the one fedmsg uses. It should also use the ZMQ authenticated sockets (server side only) rather than message signatures.

- An API that is identical to the current ``consume`` call for AMQP that connects to ZMQ instead. The ack/nack interface would be a no-op since it's using ZMQ pub/sub sockets, but ideally everything else is the same (message validation, creating the Python message objects, etc).

This way you can use the same consumer callback everywhere, Fedora infra doesn't have to expose the broker to the world, and consumers outside infra get the same level of reliability they've always had with fedmsg (no guarantees about message delivery).

@abompard, what do you think of this? @TomasTomecek, while the nitty-gritty details might not interest you, how does the overall proposal sound?

**Comment by TomasTomecek** [comment]
Sounds good. Jeremy, thanks for putting this together.

Let me comment on the two roadblocks in the present solution:
 * auth required - I'm fine with this; if it's just asking for (read-only) credentials, I can easily do that
 * no access from the Internet - this is a big one -- I can't work on my application when I can't receive those messages

> allowing unauthenticated access to the AMQP broker is a recipe for DoS attacks

Regarding the concern for DoS, is it enough to just know the dns entry and port where the service is running to be able to bring down with enough computational power? Is this what you want to prevent?

**Comment by abompard** [comment]
@jeremycline Yeah, it sounds good. Having a lighter version of fedmsg (well, a ZMQ-based client basically) for external connections seems definitely useful. There would only be subscriptions though, no publications (seems obvious but it might be worth mentioning explicitely in the docs).

**Comment by jeremycline** [comment]
> Regarding the concern for DoS, is it enough to just know the dns entry and port where the service is running to be able to bring down with enough computational power? Is this what you want to prevent?

No, the issue is how to allocate resources to clients. If we allow anyone on the Internet to create queues (which you must do to consume messages) the broker could quickly hit resource limitations. A lot of the same reasons we want a message broker - message persistence, certain delivery guarantees, etc - make it easy for malicious clients to consume server resources with little effort on their end.

There are ways to limit the damage like limit queue sizes, but it would be a non-trivial burden on the infrastructure system admins to keep going. With the proposed approach the outside world could still DoS the public ZMQ publishers, but that wouldn't damage core infrastructure applications.

> There would only be subscriptions though, no publications (seems obvious but it might be worth mentioning explicitely in the docs)

Good point, it's definitely easy to take that sort of thing as obvious when it's only obvious if you know how it's all implemented.

**Comment by mizdebsk** [comment]
>   * The interface you use to implement consumers depends on whether or not your service is inside Fedora infrastructure, and you have to change depending on where your service runs.

What do you mean? Exactly the same code and configuration can be used for consumers inside and outsides of Fedora infrastructure - just connect to fedoraproject.org on TCP port 9940 and you'll be delivered messages by busgateway through a proxy.

**Comment by jeremycline** [comment]
That's a ZeroMQ PUB socket, not an AMQP broker. This library only does AMQP. You can use a fedmsg consumer to get those messages, but we're moving all the internal stuff away from fedmsg so if it's internal it'll need to be using an AMQP client (e.g. this library which uses pika).

In any case, we talked about this a bit before DevConf and Patrick indicated running a consume-only broker outside Fedora infrastructure is probably okay with the sysadmins. The details need to be worked out, but if we do that this issue isn't a problem since you can use an AMQP client everywhere.

**Comment by jeremycline** [comment]
The message broker is now available for anyone to connect to, so I'm closing this.
