### ISSUE TITLE
Add a Sphinx autodoc generator

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/fedora-messaging#120]
It would be nice if we had a Sphinx plugin for fedora-messaging that would allow Sphinx users to point at schema objects and have Sphinx RST docs automatically generated for their schemas. I'd love that for Bodhi as an example - this way I can write some code to define my schema and get documentation on that schema in my project for free.

I use something kinda like this for Bodhi's REST API, which might be something you can look at as an example of how someone else did something similar:

https://github.com/Cornices/cornice.ext.sphinx

I think this was originally @jeremycline's idea, so credit to him!

(Is it weird that I put the documentation tag on it? It's not related to fedora-messaging's own documentation, but it is related to documentation in general ☺)

**Comment by jeremycline** [comment]
https://pypi.org/project/sphinx-jsonschema/ might be usable, possibly with some tweaking

**Comment by abompard** [comment]
In fedmsg this was done by the `fedmsg_meta_fedora_infrastructure.doc_utilities:make_topics_doc()` function

**Comment by abompard** [comment]
I've written a script in 24193da that generates [this doc](https://github.com/fedora-infra/fedora-messaging/blob/develop/docs/schemas.rst) from known schema packages. Would it work for you?

It's not published on readthedocs yet but it will be when I merge the develop branch in stable.

**Comment by bowlofeggs** [comment]
Hey @abompard! Long time, no see ☺

I no longer have a vested interest in this feature, so I think you can do whatever you like with this ticket. Hope you are well!

**Comment by abompard** [comment]
Long time no see indeed! Thankfully I let my tickets rot, which give me a chance to talk to old friends once in a while :-) Well done, me.

I hope you're well too!
