### ISSUE TITLE
RPM packaging

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fedora-messaging#13]
There should be a spec file to package this on the currently supported Fedora versions, as well as CentOS 7 and 8.

**Comment by xsuchy** [comment]
pyp2rpm can create spec/srpm which nearly work. You just have to disable %check and remove pytest-twisted from buildrequires as this module is not in Fedora.

**Comment by xsuchy** [comment]
The only thing you should do so this accepted to Fedora distro is to write a man page for fedora-messaging command.

**Comment by jeremycline** [comment]
> The only thing you should do so this accepted to Fedora distro is to write a man page for fedora-messaging command.

Cool.

@abompard, for the man page we can generate one with sphinx so we should be good to go for packaging: https://github.com/fedora-infra/fedora-messaging/blob/94b8ecbeb6efadcd8b1e6139ccf43f2028e7ca8c/docs/conf.py#L158
