### ISSUE TITLE
Twisted support

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fedora-messaging#14]
It would be nice to have Twisted support, to integrate Fedora Messaging with other network protocols and create bridges.

**Comment by abompard** [comment]
See PR #7

**Comment by jeremycline** [comment]
PR #7 is merged, but there's a little bit of work left for complete support:

- [ ] API documentation rendered in the Sphinx project.

- [ ] Client cert support. This should just be a factory to turn our configuration into a SSL context object for Twisted's TLS connection factory.

**Comment by abompard** [comment]
API docs for Twisted added in 82cf049.
