### ISSUE TITLE
Move the example schema to use the schema_utils module

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fedora-messaging#165]
https://github.com/fedora-infra/fedora-messaging/blob/be3e88534e2b15d579bcd24f9c4b7e795cb7e0b7/fedora_messaging/schema_utils.py#L27

There's a get_avatar_url function, which is redefined in the example schema package. This is confusing, so we should get rid of the one in the schema package and import the utilities.

**Comment by dvejmz** [comment]
I'll take a look at this one if you don't mind

**Comment by subhamkrai** [comment]
Hey, @jeremycline  I'm new to fedora and contributions and would like to work on this.

**Comment by jeremycline** [comment]
By all means, submit PRs. Thanks!
