### ISSUE TITLE
Clearly document what properties message schema classes should override

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fedora-messaging#166]
At the moment, it's not clear from the message API docs (https://fedora-messaging.readthedocs.io/en/stable/api.html#fedora_messaging.message.Message) that users are expected to override and provide certain properties so that filtering can be applied for things like notifications.

We should add notes to the properties users should override.

**Comment by AdamWill** [comment]
Also point to this from somewhere around https://fedora-messaging.readthedocs.io/en/stable/messages.html#schema , ideally.
