### ISSUE TITLE
clarify the differences between fedora-messaging and fedmsg

### ISSUE THREAD

**Issue by ktdreyer** [fedora-infra/fedora-messaging#17]
Hi folks, it's not clear to how https://github.com/fedora-infra/fedmsg relates to this repository. Is the fedmsg repo entirely deprecated, and this fedora-messaging repo is the bright future?

**Comment by jeremycline** [comment]
Yes. It was on my to-do list to write a more informative readme before Flock, which should make it more obvious. We're still hammering out a few small API details, but I think after Flock (next week) we'll be ready for a non-alpha release.

**Comment by ktdreyer** [comment]
Looks good! Thanks @jeremycline
