### ISSUE TITLE
RFE: Provide a consumer initialization hook

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/fedora-messaging#174]
I would like to be able to provide a function to be run once upon process start up to initialize my consumer process. This would be useful for doing things like setting up a database connection. I can do this now by having a check on each message I receive to make sure I've initialized by database, but it'd be nice to have a formal way to initialize my process.

**Comment by jeremycline** [comment]
If you define a class like:

```
class MyConsumer:
    def __init__(self):
        <setup code>

    def __call__(self, message):
        <process message here>
```

and use the class as the callback, it will be instantiated before use. If you need additional hooks, defining them should be pretty easy (we already depend on blinker so you just register a signal handler), but it might make the CLI a bit more verbose.

**Comment by bowlofeggs** [comment]
Oh I think that's actually perfect for what I'm doing - I'll send you a PR to document that (unless it's already in the docs? I didn't see it, but I might have missed it…)

**Comment by jeremycline** [comment]
On 5/15/19 10:38 PM, Randy Barlow wrote:
> Oh I think that's actually perfect for what I'm doing - I'll send you a PR to document that (unless it's already in the docs? I didn't see it, but I might have missed it…)
> 

I think there's an example in the consumer section that uses a class,
but since you missed it, it isn't as well-documented as it should be.
PRs welcome, etc.

**Comment by bowlofeggs** [comment]
I think we can say that https://github.com/fedora-infra/fedora-messaging/pull/177 fixed this issue.
