### ISSUE TITLE
RFE: aggregate and document known schema: provide list of message topics and documentation

### ISSUE THREAD

**Issue by dustymabe** [fedora-infra/fedora-messaging#180]
I typically discover and investigate message topics and body content I can use as a consumer of fedora messages by going to the [datagrepper homepage](https://apps.fedoraproject.org/datagrepper/) and scrolling to the bottom and clicking the link for [http://fedmsg.com/en/latest/topics.html](http://fedmsg.com/en/latest/topics.html). That link [currently points to a dead page](https://github.com/fedora-infra/datagrepper/pull/210/files).

When I raised this concern I was informed the documentation is out of date and we need to generate similar documentation with fedora messaging and also automate it so that it doesn't get out of date by aggregating and documenting known schema.

My goal is to have a page of documentation for every known message within fedora that a user can queue off of. This page would be very similar to https://fedora-fedmsg.readthedocs.io/en/latest/topics.html but updated automatically.

**Comment by jeremycline** [comment]
#120 is related to this in that it would be nicest if the workflow to make the docs is:

1. Write a schema
2. Add some sphinx boilerplate to your schema package so docs will be generated from the json-schema.
3. Point readthedocs.org or similar to your docs so they're automatically built and updated.
4. Add a reference to those docs in fedora-messaging (possibly with some sphinx magic to make a big list of messages by topic).

**Comment by dustymabe** [comment]
leaving note here for future self: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/6JPESNVYRZ4CFDI2VHFNXJ5YPZW6CDUO/

**Comment by abompard** [comment]
I've written a script in 24193da that generates [this doc](https://github.com/fedora-infra/fedora-messaging/blob/develop/docs/schemas.rst) from known schema packages. Would it work for you?

It's not published on readthedocs yet but it will be when I merge the develop branch in stable.

**Comment by dustymabe** [comment]
@abompard - it's definitely better than what we have now. IIRC one nice thing about the page we used to use is it included a clickable link so you could run a datagrepper query and get results back and inspect them (all in your browswer wondow). Could we get some sort of [link]() in this page as well? A large benefit is the "discoverability".

**Comment by abompard** [comment]
> IIRC one nice thing about the page we used to use is it included a clickable link so you could run a datagrepper query and get results back and inspect them (all in your browswer wondow). Could we get some sort of link in this page as well? A large benefit is the "discoverability".

Good idea, I'll add that, thanks!
