### ISSUE TITLE
Add messages header that points to the Python package for the schema

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fedora-messaging#187]
Publishers using schema add a header to identify the schema, but from the consumer side it's not obvious where to get the schema.

We can use the entry point of the message being published to inspect that package's metadata and provide things like the URL and so on. Then on the consumer side we can log more helpful messages when users are missing the schema.

**Comment by Rits1272** [comment]
Can I work on this issue @jeremycline?

**Comment by jeremycline** [comment]
Hi @Rits1272,

I no longer have the time to work on this project so I can't commit to walking you through the necessary steps for this. Nor am I sure that anyone is around to review your work, accept it, and then release it. However, no one else is working on this as far as I know so if it's something you'd like to do despite those things, you're more than welcome to.
