### ISSUE TITLE
Documentation states that HaltConsumer is raised when the callback raises an exception

### ISSUE THREAD

**Issue by mprahl** [fedora-infra/fedora-messaging#215]
The [documentation](https://fedora-messaging.readthedocs.io/en/stable/tutorial/exceptions.html#when-consuming) states that when the consumer raises an unexpected exception, it will "bubble up in the consumer as a HaltConsumer exception."

When looking at the code, I don't see where this is happening. When the callback raises an unexpected exception, it is reraised as is:
https://github.com/fedora-infra/fedora-messaging/blob/104363fa91196c0ce5cb7c84339d0f12fe5c6334/fedora_messaging/twisted/protocol.py#L254-L259

As a side note, it'd be better to use `raise` rather than `raise e` to preserve the original traceback.

On the `consume` function, it also doesn't wrap the exception as a `HaltConsumer` exception:
https://github.com/fedora-infra/fedora-messaging/blob/104363fa91196c0ce5cb7c84339d0f12fe5c6334/fedora_messaging/api.py#L240-L246

For what it's worth, I prefer the original exception being raised, so if the documentation is wrong, I suggest correcting the documentation rather than changing the behavior.

**Comment by jeremycline** [comment]
> The [documentation](https://fedora-messaging.readthedocs.io/en/stable/tutorial/exceptions.html#when-consuming) states that when the consumer raises an unexpected exception, it will "bubble up in the consumer as a HaltConsumer exception."
> 
> When looking at the code, I don't see where this is happening. When the callback raises an unexpected exception, it is reraised as is:
> 
> https://github.com/fedora-infra/fedora-messaging/blob/104363fa91196c0ce5cb7c84339d0f12fe5c6334/fedora_messaging/twisted/protocol.py#L254-L259
> 
> As a side note, it'd be better to use `raise` rather than `raise e` to preserve the original traceback.
> 

While I believe this is not technically true in Python 3 (you'll get a backtrace, then a "while handling the previous exception..."), I don't have a problem with the change.

> On the `consume` function, it also doesn't wrap the exception as a `HaltConsumer` exception:
> 
> https://github.com/fedora-infra/fedora-messaging/blob/104363fa91196c0ce5cb7c84339d0f12fe5c6334/fedora_messaging/api.py#L240-L246
> 
> For what it's worth, I prefer the original exception being raised, so if the documentation is wrong, I suggest correcting the documentation rather than changing the behavior.

Looking at the code in 1.7.2 it *used* to wrap the exception in a HaltConsumer exception, but now it doesn't. I don't remember my reasoning for doing so anymore, so I suppose if we change the referenced documentation, add a note to the v2.0.0 breaking changes about the API change, and update the API docblock to note it raises `Exception` if the consumer doesn't handle its errors properly it'd be best to leave it as-is. @abompard?

**Comment by abompard** [comment]
Yeah I was looking at that too, I think it's a change that occured when we moved everything to Twisted. I also think it's better to update the documentation.
