### ISSUE TITLE
Docs should list to canonical source of topics

### ISSUE THREAD

**Issue by michaelgugino** [fedora-infra/fedora-messaging#226]
There is no link or reference to datagrepper from this project.

Datagrepper also has a bad link to a list of topics.

https://github.com/fedora-infra/datagrepper/issues/226

**Comment by abompard** [comment]
While this would be useful, it would be hard to maintain and would quickly become outdated. We could however have a list of schema packages, it would be less maintenance and we could build the list of topics from there.

**Comment by abompard** [comment]
This has been done in #242. The list of known schema with their included topics is available [in the develop docs](https://fedora-messaging.readthedocs.io/en/develop/schemas.html). It will be in the standard (`stable`) docs once we merge the develop branch into the stable branch prior to releasing a new version.

If you know of more schema packages, please let me know or add them to the `docs/schema-packages.txt` file.
