### ISSUE TITLE
Document that the `passive_declares` config value is mandatory on Fedora's private vhost

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fedora-messaging#245]
It's a common mistakes for users of Fedora's `/pubsub` vhost to forget to set `passive_declares` to `true`, but it's apparently not documented here.

**Comment by vidit-maheshwari** [comment]
I am an outreachy applicant and I want to contribute to this issue can you please elaborate for better understanding or provide with the resources required to solve this issue

**Comment by abompard** [comment]
Sure. This is a documentation issue, so I'd say that the first step is to clone the repo and build the docs in their current state.

**Comment by nwekealex65** [comment]
@abompard I saw you assigned this issue to someone already. I have done a work on this, can I make a pull request for you to review?

**Comment by abompard** [comment]
@vidit-maheshwari Are you still working on this?

**Comment by vidit-maheshwari** [comment]
@abompard i was working on that but i have my university exams right now so can't create a pull request.

**Comment by nwekealex65** [comment]
Okay then I will make a pull request now, make a review

**Comment by nwekealex65** [comment]
I just did
