### ISSUE TITLE
Request for docs: how to migrate from message scheme version N to version N+1

### ISSUE THREAD

**Issue by praiskup** [fedora-infra/fedora-messaging#247]
It is expected that message schemes evolve. There's a small note about the message
[scheme versioning](https://fedora-messaging.readthedocs.io/en/stable/messages.html#message-conventions) and `BaseMessage` providing an "interface".

I though struggle to understand how the migration from one version to another should be implemented (and communicated).
We can start sending a new message format, though it will break older consumers.

Are we supposed to send (for a certain time period) multiple messages in multiple versions concurrently?  Wouldn't this generally overwhelm the message bus?  

What about message "topics"?  Should they change as well?  Should version be part of the message topic, e.g.
   `myservice.myevent.v1`, and installed into entry points?

Has this happened before, among the [example messages]( https://github.com/fedora-infra/fedora-messaging/blob/c7c2c20cb0120644dd6db116e1b48b60e27c6d70/docs/schema-packages.txt#L3-L10) where we could get the inspiration?

**Comment by abompard** [comment]
It's an excellent question, one that I tried to make a note about in #227. I'll try to answer your questions here, but it should really be documented.

I recommend including the schema version in the topic itself, as you pointed out, with `myservice.myevent.v1`, and changing that version with backwards-incompatible schema changes. I also recommend sending the two versions simultaneously for "a while". I leave the duration to your appreciation, it probably depends on how many different consumers you expect to have, inside of Fedora infra only or outside too, etc. This duration can possibly range from weeks to months, possibly a year, I don't know. The bus is very very far from being overwhelmed by messages, so you don't need to worry about that.
This way, consumers who subscribe to `v1` know that they will not break when `v2` arrives, and can choose to subscribe to the `v2` topic when they are ready to handle the new format.

Does it answer your questions?

**Comment by praiskup** [comment]
Yes, but one missing thing....

> installed into entry points?

Is it still a recommended way to install "entry points" for messages, so messages are automatically instantiated?
I fail to see it in the documentation currently.

**Comment by abompard** [comment]
Yeah there's no way around that, all schema classes must have a corresponding entry point, that's how a receiver can know which class to instanciate.

**Comment by praiskup** [comment]
Thank you for the docs, very appreciated!
