### ISSUE TITLE
Add accessors to the Message class

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fedora-messaging#28]
Fedmsg has a lot of accessors available for consumers, let's discuss what we want to keep.

Here's what I found in `fedmsg-meta`, and my comments:
* `title`: replaced by `summary`
* `subtitle`: replaced by `__str__`
* `subjective`: it hasn't really been used, let's drop it
* `long_form` (paragraphs of text about a message): it would be useful for email notifications
* `lexer` (pygments lexer that can be applied to the long_form): not sure we want that, it's only implemented for github and scm messages
* `link`: that would be useful I think (maybe renamed as `url`? I don't find "link" very clear)
* `icon` and `secondary_icon`: those are usually the app icon and the agent's avatar. They are used, so I think we should keep them, but rename them to `app_icon` and `agent_avatar` just to be clearer. (see `fedmsg_meta_fedora_infrastructure.fasshim`).
* `usernames` (a set of FAS usernames associated with the message): this would be necessary for FMN
* `packages` (a set of package names associated with a message): this would be necessary for FMN
* `objects`: unclear, we should drop it and leave it to publishers to provide a precise accessor in their API.
* `emails`: we can leave that to publishers and not make it standard
* `avatars` (dict of avatar URLs associated with a message): unused, drop it

**Comment by pypingou** [comment]
Could it be that the lexer may be used by datagrepper to show the message with a certain high-lighting?

Is ``subjective`` used by the conglomerating code in FMN?

**Comment by jeremycline** [comment]
> * title: replaced by summary
> * subtitle: replaced by __str__
> * long_form (paragraphs of text about a message): it would be useful for email notifications

Hmm. I was thinking that ``__str__`` would basically be the long-form that you'd normally print to a user. Emails would be ``summary`` as the subject, ``__str__`` as the body. IRC would just be summary. Is this enough granularity?

> * lexer (pygments lexer that can be applied to the long_form): not sure we want that, it's only implemented for github and scm messages

I vote drop here. If those messages want lexed output, they can add their own method/property to do so.

> * link: that would be useful I think (maybe renamed as url? I don't find "link" very clear)

Yes, probably useful for users. +1 on the rename to url, and we can provide a sane default in the base Message.

> * icon and secondary_icon: those are usually the app icon and the agent's avatar. They are used, so I think we should keep them, but rename them to app_icon and agent_avatar just to be clearer. (see fedmsg_meta_fedora_infrastructure.fasshim).

Works for me. Again, we can make reasonable defaults and it's a totally opt-in, if you want to make your messages shiny sort of deal.

All the rest I agree with dropping. One last thing is that we should add an importance attribute. Example usage: a successful build could be INFO level, a build failure is ERROR. A failed test would be WARNING or ERROR depending on the test. A passed test is INFO. That way we can set up sane filters for users.

**Comment by abompard** [comment]
> Hmm. I was thinking that `__str__` would basically be the long-form that you'd normally print to a user. Emails would be summary as the subject, `__str__` as the body. IRC would just be summary. Is this enough granularity?

That would work too. In general `title` was unused and `subtitle` was used as a one-line summary, so I think we can rename the existing `subtitle` to `summary`, and the existing `long_form` to `__str__`.

> Is subjective used by the conglomerating code in FMN?

It doesn't look like it, and anyway since it does not make much sense to receive notification for one's own actions (I know what I just did :-) ), `subjective` isn't very appropriate there.

I'll prepare a PR.
