### ISSUE TITLE
PublisherSession.publish throws pika.exceptions.ChannelClosed

### ISSUE THREAD

**Issue by sebwoj** [fedora-infra/fedora-messaging#30]
PublisherSession.publish throws pika.exceptions.ChannelClosed during "Resetting connection to..."
Example test case: try to publish message with invalid "publish_exchange"

**Comment by jeremycline** [comment]
Fixed by #31 

For future reference, if you add ``fixes #<issue number>`` in your commit message (I like to do it after the body and before the sign-off) Github will automatically close the issue when the commit is merged into the default branch :smiley:
