### ISSUE TITLE
Security policy question

### ISSUE THREAD

**Issue by KhaledAchech** [fedora-infra/fedora-messaging#314]
👋 Hello Everyone,

I'm Khaled Achech a passionate developer but I would like to start contributing more to open-source projects. This could be my first time contributing to an open-source project. I've noticed in security tab that there is no security policy for this repository and I was wondering if it's okay for me to add one as my first contribution to the project ?

**Comment by abompard** [comment]
Sure, go ahead, thanks :-)

**Comment by KhaledAchech** [comment]
Awesome, Thank you :)

**Comment by KhaledAchech** [comment]
Hi @abompard,

I wanted to let you know that I submitted a PR for this issue. I'm open to any feedback or adjustments you may have.
Thanks for your time ^^

**Comment by KimFarida** [comment]
@abompard  I see this issue is still open, may i please work on it?

**Comment by gridhead** [comment]
Fixed via #315. Closing.
