### ISSUE TITLE
Add a replay command

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fedora-messaging#332]
Add a replay command that would get a message from datagrepper and replay it to the bus.

Get inspiration from https://github.com/fedora-infra/the-new-hotness/blob/master/devel/fedora_messaging_replay.py but use `message.load_message()` to preserve headers.

**Comment by Freedisch** [comment]
seems, like a good issue for me, I'm preparing a PR

**Comment by maha-sachin** [comment]
Hi, I'm Mahalakshmi from OutReachy Interen, Canada, a passionate developer and I would like to start contributing more to open-source projects. Could you please let me know if it would be possible for me to take on this task? I'm keen to get started and make a positive impact on the project.

**Comment by NyuydineBill** [comment]
@Freedisch  how can i get in contact please? I've followed on twitter but can't send message

**Comment by amehclibton** [comment]
I think I can handle this.

**Comment by simideveloper** [comment]
hi I am an outreachy applicant this issue seems to be good for newcomers and is still open can I work on this?

**Comment by abompard** [comment]
Freedisch has started working on it, so please find another issue
