### ISSUE TITLE
"--amqp-url" parameter unused

### ISSUE THREAD

**Issue by sebwoj** [fedora-infra/fedora-messaging#45]
In cli, parameter "--amqp-url" is not used.
User is not able to pass "amqp-url" to  _session.ConsumerSession(except config file)
Also, impossible to pass "amqp-url" via api.publish to _session.PublisherSession(except config file)

**Comment by jeremycline** [comment]
Indeed. I think I started to wire this up and then left it until I decided if it was worth it and didn't tidy up.

I think it'd be best to remove it from the CLI and require it to be specified via the configuration for now. If users really want to specify it via the CLI or API, we can look at adding it, but until then let's keep it simple.
