### ISSUE TITLE
Attempt to get not existing pika.exceptions.ChannelClosed attributes

### ISSUE THREAD

**Issue by sebwoj** [fedora-infra/fedora-messaging#77]
In _session.ConsumerSession._on_channel_close, we are trying to get:
        if isinstance(reply_code_or_reason, pika_errs.ChannelClosed): 
            reply_code = reply_code_or_reason.reply_code 
            reply_text = reply_code_or_reason.reply_text 

I think that attrs reply_code and reply_text are not existing in object ChannelClosed.

**Comment by sebwoj** [comment]
It looks like the same issue in "_on_connection_close" too.

**Comment by jeremycline** [comment]
I believe this is fixed.
