### ISSUE TITLE
Fedora RPM package

### ISSUE THREAD

**Issue by xsuchy** [fedora-infra/fedora-messaging#80]
It is nice that this project has spec file, but we really need this package in Fedora. Otherwise, we cannot start migrating to fedora-messaging.

Please see:
https://fedoraproject.org/wiki/New_package_process_for_existing_contributors
https://fedoraproject.org/wiki/Join_the_package_collection_maintainers

**Comment by xsuchy** [comment]
If users (which means projects like Copr and FAF) should migrate to fedora-messaging, then this package must be in Fedora main. And I do not see it there:
https://koji.fedoraproject.org/koji/search?match=glob&type=package&terms=python-fedora-messaging

**Comment by jeremycline** [comment]
Bleh, it ended up being named fedora-messaging, my bad: https://src.fedoraproject.org/rpms/fedora-messaging and https://koji.fedoraproject.org/koji/packageinfo?packageID=27527
